"""Auto-generated. Do not edit by hand.

Regenerate with:
    uv run python .kiro/hooks/scripts/refresh_connect_flow_language.py

Source pages:
    https://docs.aws.amazon.com/connect/latest/devguide/flow-language-actions.html
    https://docs.aws.amazon.com/connect/latest/devguide/contact-actions.html
    https://docs.aws.amazon.com/connect/latest/devguide/flow-control-actions.html
    https://docs.aws.amazon.com/connect/latest/devguide/interactions.html
    https://docs.aws.amazon.com/connect/latest/devguide/participant-actions.html
"""

VALID_ACTION_TYPES: frozenset[str] = frozenset({
    "AssociateContactToCustomerProfile",
    "CheckHoursOfOperation",
    "CheckMetricData",
    "CheckOutboundCallStatus",
    "CheckVoiceId",
    "Compare",
    "CompleteOutboundCall",
    "ConnectParticipantWithLexBot",
    "CreateCallbackContact",
    "CreateCase",
    "CreateCustomerProfile",
    "CreateTask",
    "CreateWisdomSession",
    "DequeueContactAndTransferToQueue",
    "DisconnectParticipant",
    "DistributeByPercentage",
    "EndFlowExecution",
    "EndFlowModuleExecution",
    "GetCalculatedAttributesForCustomerProfile",
    "GetCase",
    "GetCustomerProfile",
    "GetCustomerProfileObject",
    "GetMetricData",
    "GetParticipantInput",
    "InvokeFlowModule",
    "InvokeLambdaFunction",
    "Loop",
    "MessageParticipant",
    "MessageParticipantIteratively",
    "ResumeContact",
    "ShowView",
    "StartOutboundChatContact",
    "StartVoiceIdStream",
    "TagContact",
    "TransferContactToAgent",
    "TransferContactToQueue",
    "TransferToFlow",
    "UnTagContact",
    "UpdateCase",
    "UpdateContactAttributes",
    "UpdateContactCallbackNumber",
    "UpdateContactData",
    "UpdateContactEventHooks",
    "UpdateContactMediaProcessing",
    "UpdateContactMediaStreamingBehavior",
    "UpdateContactRecordingAndAnalyticsBehavior",
    "UpdateContactRecordingBehavior",
    "UpdateContactRoutingBehavior",
    "UpdateContactTargetQueue",
    "UpdateContactTextToSpeechVoice",
    "UpdateCustomerProfile",
    "UpdateFlowAttributes",
    "UpdateFlowLoggingBehavior",
    "UpdatePreviousContactParticipantState",
    "UpdateRoutingCriteria",
    "Wait",
})

# Maps every Action type to its category, useful for error messages and
# catalog grouping.
ACTION_CATEGORY: dict[str, str] = {
    "AssociateContactToCustomerProfile": "Interactions",
    "CheckHoursOfOperation": "Flow control",
    "CheckMetricData": "Flow control",
    "CheckOutboundCallStatus": "Flow control",
    "CheckVoiceId": "Flow control",
    "Compare": "Flow control",
    "CompleteOutboundCall": "Contact",
    "ConnectParticipantWithLexBot": "Participant",
    "CreateCallbackContact": "Interactions",
    "CreateCase": "Contact",
    "CreateCustomerProfile": "Interactions",
    "CreateTask": "Contact",
    "CreateWisdomSession": "Contact",
    "DequeueContactAndTransferToQueue": "Contact",
    "DisconnectParticipant": "Participant",
    "DistributeByPercentage": "Flow control",
    "EndFlowExecution": "Flow control",
    "EndFlowModuleExecution": "Contact",
    "GetCalculatedAttributesForCustomerProfile": "Interactions",
    "GetCase": "Contact",
    "GetCustomerProfile": "Interactions",
    "GetCustomerProfileObject": "Interactions",
    "GetMetricData": "Flow control",
    "GetParticipantInput": "Participant",
    "InvokeFlowModule": "Contact",
    "InvokeLambdaFunction": "Interactions",
    "Loop": "Flow control",
    "MessageParticipant": "Participant",
    "MessageParticipantIteratively": "Participant",
    "ResumeContact": "Contact",
    "ShowView": "Participant",
    "StartOutboundChatContact": "Contact",
    "StartVoiceIdStream": "Flow control",
    "TagContact": "Contact",
    "TransferContactToAgent": "Contact",
    "TransferContactToQueue": "Contact",
    "TransferToFlow": "Flow control",
    "UnTagContact": "Contact",
    "UpdateCase": "Contact",
    "UpdateContactAttributes": "Contact",
    "UpdateContactCallbackNumber": "Contact",
    "UpdateContactData": "Contact",
    "UpdateContactEventHooks": "Contact",
    "UpdateContactMediaProcessing": "Contact",
    "UpdateContactMediaStreamingBehavior": "Contact",
    "UpdateContactRecordingAndAnalyticsBehavior": "Contact",
    "UpdateContactRecordingBehavior": "Contact",
    "UpdateContactRoutingBehavior": "Contact",
    "UpdateContactTargetQueue": "Contact",
    "UpdateContactTextToSpeechVoice": "Contact",
    "UpdateCustomerProfile": "Interactions",
    "UpdateFlowAttributes": "Flow control",
    "UpdateFlowLoggingBehavior": "Flow control",
    "UpdatePreviousContactParticipantState": "Contact",
    "UpdateRoutingCriteria": "Flow control",
    "Wait": "Flow control",
}
